sonar.projectKey=zmathmatos_fiap-soat-execution-service
sonar.organization=zmathmatos
sonar.projectName=fiap-soat-execution-service

sonar.sources=src
sonar.tests=tests,features
sonar.exclusions=src/infrastructure/database/typeorm/migrations/**,src/server.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
